# Generated by Django 3.0.4 on 2020-03-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
