# Generated by Django 3.0.4 on 2020-03-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='job_openings/images'),
        ),
    ]
